# Generated by Django 4.1.4 on 2023-01-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='count',
        ),
        migrations.AddField(
            model_name='task',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
