# Generated by Django 4.1.4 on 2023-01-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_count_task_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='count',
        ),
    ]
