# Generated by Django 4.1.4 on 2023-01-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_task_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
