# Generated by Django 4.1.4 on 2022-12-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_alter_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpcode',
            old_name='code',
            new_name='otp',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.JSONField(default=dict),
        ),
    ]
