# Generated by Django 4.1.4 on 2022-12-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_rename_code_otpcode_otp_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
