# Generated by Django 4.1.4 on 2023-01-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0010_alter_user_full_name_alter_user_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_phone_verified',
        ),
    ]
