# Generated by Django 4.1.4 on 2023-01-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0011_remove_user_is_admin_remove_user_is_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
