# Generated by Django 4.1.4 on 2023-01-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0012_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='limit_project',
            field=models.IntegerField(default=10),
        ),
    ]
