# Generated by Django 4.1.4 on 2023-01-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0014_rename_limit_project_user_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.BooleanField(default=False),
        ),
    ]
