# Generated by Django 4.1.4 on 2023-02-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meta',
            options={'get_latest_by': ['created']},
        ),
    ]
