# Generated by Django 4.1.4 on 2023-02-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_alter_meta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
