# Generated by Django 4.1.4 on 2023-01-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversazione',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='conversazione',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='file/'),
        ),
    ]
