# Generated by Django 4.1.4 on 2023-01-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massages', '0002_remove_conversazione_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversazione',
            name='attachments',
            field=models.FileField(blank=True, default=None, null=True, upload_to='file/'),
        ),
    ]
