# Generated by Django 4.1.4 on 2023-02-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massages', '0004_channel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='state',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
