# Generated by Django 4.1.4 on 2023-02-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massages', '0005_channel_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(default='Mychannel', max_length=24),
        ),
    ]
